=begin
#WhenIWork

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'wheniwork-ruby/api_client'
require 'wheniwork-ruby/api_error'
require 'wheniwork-ruby/version'
require 'wheniwork-ruby/configuration'

# Models
require 'wheniwork-ruby/models/payroll'
require 'wheniwork-ruby/models/payrolls_response'
require 'wheniwork-ruby/models/position'
require 'wheniwork-ruby/models/position_response'
require 'wheniwork-ruby/models/shift'
require 'wheniwork-ruby/models/shifts_response'
require 'wheniwork-ruby/models/time'
require 'wheniwork-ruby/models/times_response'
require 'wheniwork-ruby/models/user'
require 'wheniwork-ruby/models/users_response'

# APIs
require 'wheniwork-ruby/api/default_api'

module WhenIWork
  class << self
    # Customize default settings for the SDK using block.
    #   WhenIWork.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
