=begin
Wheniwork

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module WhenIWork
  class Shift
    include WhenIWork::Response

    attr_accessor :start_time
    attr_accessor :end_time
    attr_accessor :created_at
    attr_accessor :updated_at
    attr_accessor :notified_at
    attr_accessor :id
    attr_accessor :account_id
    attr_accessor :user_id
    attr_accessor :location_id
    attr_accessor :alerted
    attr_accessor :is_open
    attr_accessor :acknowledged
    attr_accessor :notes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'start_time' => :'start_time',
        :'end_time' => :'end_time',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'notified_at' => :'notified_at',
        :'id' => :'id',
        :'account_id' => :'account_id',
        :'user_id' => :'user_id',
        :'location_id' => :'location_id',
        :'alerted' => :'alerted',
        :'is_open' => :'is_open',
        :'acknowledged' => :'acknowledged',
        :'notes' => :'notes'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'start_time' => :'DateTime',
        :'end_time' => :'DateTime',
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime',
        :'notified_at' => :'DateTime',
        :'id' => :'Integer',
        :'account_id' => :'Integer',
        :'user_id' => :'Integer',
        :'location_id' => :'Integer',
        :'alerted' => :'BOOLEAN',
        :'is_open' => :'BOOLEAN',
        :'acknowledged' => :'Integer',
        :'notes' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'start_time')
        self.start_time = attributes[:'start_time']
      end

      if attributes.has_key?(:'end_time')
        self.end_time = attributes[:'end_time']
      end

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.has_key?(:'notified_at')
        self.notified_at = attributes[:'notified_at']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.has_key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.has_key?(:'location_id')
        self.location_id = attributes[:'location_id']
      end

      if attributes.has_key?(:'alerted')
        self.alerted = attributes[:'alerted']
      end

      if attributes.has_key?(:'is_open')
        self.is_open = attributes[:'is_open']
      end

      if attributes.has_key?(:'acknowledged')
        self.acknowledged = attributes[:'acknowledged']
      end

      if attributes.has_key?(:'notes')
        self.notes = attributes[:'notes']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          start_time == o.start_time &&
          end_time == o.end_time &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          notified_at == o.notified_at &&
          id == o.id &&
          account_id == o.account_id &&
          user_id == o.user_id &&
          location_id == o.location_id &&
          alerted == o.alerted &&
          is_open == o.is_open &&
          acknowledged == o.acknowledged &&
          notes == o.notes
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [start_time, end_time, created_at, updated_at, notified_at, id, account_id, user_id, location_id, alerted, is_open, acknowledged, notes].hash
    end
  end
end
